import Head from "next/head";
import Image from "next/image";
import { GetServerSideProps } from "next";
import styles from "@/styles/Home.module.css";
import MySpaceCard from "@/components/layouts/MySpaceCard";
import InfoCard from "@/components/modules/info-cards";

import { data } from "../static";

/**
 * Need 'experience' query param to hide and show cards, change about hide media player and comments
 *
 * need experience route to scroll to experience
 * need resume route to download resume
 */

export default function Home(props: any) {
  const {
    overview,
    social,
    contact,
    about,
    education,
    associations,
    experience,
    contributions,
    projects,
  } = props;

  return (
    <>
      <Head>
        <title>erockdotdev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.column}>
          <InfoCard data={overview} />
          <InfoCard data={social} />
          <InfoCard data={contact} />
          <InfoCard data={about} />
          <InfoCard data={education} />
          <InfoCard data={associations} />
        </div>
        <div className={styles.column}>
          <MySpaceCard title="MediaPlayer"></MySpaceCard>
          {/* <MySpaceCard title="Events"></MySpaceCard> */}
          <MySpaceCard title="Posts">
            <p>Pined</p>
            <p>Recent</p>
            <p>See More</p>
          </MySpaceCard>
          <InfoCard id="experience" data={experience} />
          <InfoCard id="contributions" data={contributions} />
          <InfoCard id="projects" data={projects} />
          <MySpaceCard title="Friends"></MySpaceCard>
          <MySpaceCard title="Comments"></MySpaceCard>
        </div>
      </main>
      <footer>PUNCH THE MONKEY</footer>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async context => {
  return {
    props: {
      overview: data.overview,
      social: data.social,
      contact: data.contact,
      about: data.about,
      education: data.education,
      associations: data.associations,
      experience: data.experience,
      contributions: data.contributions,
      projects: data.projects,
    },
  };
};
